name: App Playwright Tests
on:
  push:
    branches: [ main, master ]
    paths: [ 'app/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'app/**' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./app
        run: yarn
      - name: Install Playwright Browsers
        working-directory: ./app
        run: yarn playwright install --with-deps
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 90
      - name: Run Playwright tests
        working-directory: ./app
        run: yarn playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 30
