name: App Playwright Tests
on:
  push:
    branches: [ main, master ]
    paths: [ 'app/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'app/**' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      working-directory: ./app
      run: yarn
    - name: Install Playwright Browsers
      working-directory: ./app
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./app
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: app/playwright-report/
        retention-days: 30
